package com.bepcms.pcms.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * @author lidongsheng 2021/11/20 11:53
 * @version V1.0
 */
@Getter
@AllArgsConstructor
public enum SsoEnum {

    SYSTEM_ERROR("SYSTEM_ERROR", "系统错误"),
    SYSTEM_ERROR_REDIRECT_ERROR("SYSTEM_ERROR_REDIRECT_ERROR", "重定向异常"),
    SYSTEM_ERROR_URL_ENCODE_ERROR("SYSTEM_ERROR_URL_ENCODE_ERROR", "URL编码失败"),
    SYSTEM_ERROR_URL_DECODE_ERROR("SYSTEM_ERROR_URL_DECODE_ERROR", "URL解码失败"),

    /************************json转换错误码***********************/
    JSON_ERROR_JSON_TO_OBJECT_ERROR("12001", "json转换失败"),
    JSON_ERROR_OBJECT_TO_JSON_ERROR("12002", "json转换失败"),

    ROLE_ERROR_SWITCH_ROLE_USER_IS_NOT_LOGIN("ROLE_ERROR_SWITCH_ROLE_USER_IS_NOT_LOGIN", "当前用户未登录"),
    ROLE_ERROR_SWITCH_ROLE_USER_NAME_IS_NOT_EXIST("ROLE_ERROR_SWITCH_ROLE_USER_NAME_IS_NOT_EXIST", "用户名称不存在"),

    ROLE_ERROR_BACK_ROLE_USER_IS_NOT_LOGIN("ROLE_ERROR_BACK_ROLE_USER_IS_NOT_LOGIN", "当前用户未登录"),

    REQUEST_ENCRYPTION_NAUGHTY_IS_NOT_EXIST("REQUEST_ENCRYPTION_NAUGHTY_IS_NOT_EXIST", "Ds-Naughty不存在"),
    REQUEST_ENCRYPTION_BODY_IS_NOT_EXIST("REQUEST_ENCRYPTION_BODY_IS_NOT_EXIST", "body[Ds-Naughty]不存在"),
    REQUEST_ENCRYPTION_DECRYPT_ERROR("REQUEST_ENCRYPTION_DECRYPT_ERROR", "Ds-Naughty解密失败"),

    KAPTCHA_ERROR_KAPTCHA_IS_NOT_NULL("KAPTCHA_ERROR_KAPTCHA_IS_NOT_NULL", "验证码不能为空"),
    KAPTCHA_ERROR_KAPTCHA_CREATE_FAILT("KAPTCHA_ERROR_KAPTCHA_CREATE_FAILT", "验证码生成失败"),
    KAPTCHA_ERROR_KAPTCHA_NOT_EXIST("KAPTCHA_ERROR_KAPTCHA_NOT_EXIST", "验证码不存在"),
    KAPTCHA_ERROR_KAPTCHA_INCORRECT("KAPTCHA_ERROR_KAPTCHA_INCORRECT", "验证码错误"),
    KAPTCHA_ERROR_KAPTCHA_TIMEOUT("KAPTCHA_ERROR_KAPTCHA_TIMEOUT", "验证码超时"),

    REFRESH_USER_ERROR_USER_IS_NOT_LOGIN("REFRESH_USER_ERROR_USER_IS_NOT_LOGIN", "用户未登录"),
    REFRESH_USER_ERROR_USER_IS_NOT_EXIST("REFRESH_USER_ERROR_USER_IS_NOT_EXIST", "用户不存在"),

    AMC_ERROR_REST_ERROR("AMC_ERROR_REST_ERROR", "远程服务调用异常"),

    URL_ERROR_HOST_IS_NOT_NULL("URL_ERROR_HOST_IS_NOT_NULL", "Host不能为空"),
    URL_ERROR_HOST_INVALID("URL_ERROR_HOST_INVALID", "Host域名不合法"),


    LOGIN_ERROR_CLOUD_USER_NAME_IS_NOT_NULL("LOGIN_ERROR_CLOUD_USER_NAME_IS_NOT_NULL", "云账号名称不能为空"),
    LOGIN_ERROR_IAM_USER_NAME_IS_NOT_NULL("LOGIN_ERROR_IAM_USER_NAME_IS_NOT_NULL", "IAM用户名称不能为空"),
    LOGIN_ERROR_PASSWORD_IS_NOT_NULL("LOGIN_ERROR_PASSWORD_IS_NOT_NULL", "密码不能为空"),


    ;

    /**
     * 错误码
     */
    private String code;

    /**
     * 错误描述
     */
    private String desc;
}
