#spring.datasource.url=jdbc:mysql://localhost:3306/pcms
#spring.datasource.username=root
#spring.datasource.password=wyh77598.
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

#默认使用配置
spring:
    profiles:
        active: dev
    datasource:
        jdbc.url: jdbc:mysql://localhost:3306/pcms?useSSL=false
        jdbc.username: root
        password: wyh77598.
        driver-class-name: com.mysql.jdbc.Driver

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
    typeAliasesPackage: xml
    mapper-locations: classpath:xml/*.xml